### PR TITLE
added paket instructions

### PR DESCRIPTION
**Pull request by TonyAbell**
not everyone knows about paket.

### CODE REVIEW

**Comment by tpetricek** [comment]
The way the project is setup, you should not need to run paket explicitly. In fact, it breaks things (as you found out in #66). 

There is some custom stuff in the generated `fsproj` file and so building the project should restore all dependencies (and it should even happen automatically when the project is created).

Or did you have to dun `paket update` by hand? (If so, that's odd...)

**Comment by TonyAbell** [comment]
there is no need to explicitly run Paket, and it will break the solution.

**Comment by forki** [comment]
Why does paket  break the solution? What's wrong?

**Comment by tpetricek** [comment]
Because of https://github.com/fsprojects/Paket/issues/566#issuecomment-71388754 - Paket replaces our manually set `<Private>False</Private>` with the default `<Private>True</Private>`.

**Comment by forki** [comment]
I guess you want this: https://github.com/fsprojects/Paket/issues/569?

**Comment by tpetricek** [comment]
Wow, yes, that would certainly solve the problem (but I actually think FsLab runner needs redesign anyway - placing the compiled binary into `packages` is such a hack... ).

**Pull request closed without merging**
