### PR TITLE
Convert to Paket

### PR DESCRIPTION
**Pull request by forki**
- [X] Convert building solution to Paket
- [ ] Convert created FsLab to Paket
- [ ] Convert created FsLab.Runner to Paket
- [ ] web documentation

### CODE REVIEW

**Comment by forki** [comment]
I'm stuck. I don't really know how to test this.

/cc @tpetricek

**Comment by tpetricek** [comment]
Give me a day or two to finish the Deedle and R provider conversions & then I'll merge this!

[Insert animated GIF of a hamster running crazily on a wheel]

**Comment by tpetricek** [comment]
I ticked off the second checkbox with this check-in: https://github.com/tpetricek/FsLab/commit/2c1d81d0502f03331c21242e2cef9386d0928990

>  - In `FsLab.fsx`, generate `#I` for both directory with version
   and directory without version (to support both Paket and NuGet)
 - Add `FsLab` and `FsLab.Runner` to `paket.referneces` and `paket.lock`
   of FsLab Journal template (it depends on both). This is a hack because
   the package does not exist at the time of build
 - Do not look for `packages` in random places - relative reference seems to work
   (this was probably issue with earlier versions of F#)
 - Paket always puts packages into the project folder (not solution folder)
   so we do not need `#I ".."` in various places.
 - Include all template files in project - this seems to be required -
   otherwise, VS will not copy them (???)
 - Fix `<HintPath>` values in the journal template so that they point to
   project directory (I guess this could also just be `.` - but it cannot
   be `../../` which was there before)
 - Inline `paket.targets` into the Journal template - this sucks, but
   VS apparently reads the project before extracting other files, so this
   cannot be in a separate file. Also, did various path fixes here

Feedback and suggestions on how to improve this are welcome! The third checkbox is relatively minor - FsLab.Runner has some additional stuff that makes it possible to generate latex via command line, but this was never designed to do much more than that... It really only needs to download FAKE. But I guess we can use Paket to do that.

**Comment by tpetricek** [comment]
OK - a few more tweaks were needed to make `paket update` works, but everything looks good now. 

I also finished converting the FsLab.Runner (the files from there are copied to the root of the project on the first build - that is when you create a project - and if you use them for `build pdf`, then they lazily install FAKE and build `build.fsx`). We have Paket already installed (when building the project after it is created), so we can just call it.

Again, feedback is welcome. The commit is: https://github.com/tpetricek/FsLab/commit/087edc92294bc886acabb9776e0d2dda6709c5a9

>  - Remove explicit RazorEngine dependencies (this is included in F# Formatting)
 - FsLab should not depend on FsLab (ho ho ho!)
 - Rename `paket.references` to `paket.references.template` because this *needs*
   to contain reference to FsLab (which confuses `paket update`)
 - Run `paket update` to update all versions!
 - Make references non-local in `src/journal/FsLab.Journal.fsproj` (this is needed
   to make the journal runner reference the same DLLs as the script - which is
   needed to make formatters work - i.e. avoid loading the same type from two
   places which breaks things). `FSharp.Compiler.Service.Interactive` *must* be
   copied and `FSharp.Core` *must not* (not sure why).
 - Install FAKE via Paket when `build.cmd` is used to produce HTML/PDF

**Pull request merged**
